### ISSUE TITLE
[FE] Feat: 마일스톤 페이지 기능 구현 마무리

### ISSUE THREAD

**Issue by hoongding** [hoongding/issue-tracker#139]
## 💡 Issue
[FE] Feat: 마일스톤 페이지 기능 구현 마무리

## 📝 Todo
- [x] #182
- [x] 마일스톤 편집 기능 - PATCH
- [x] 마일스톤 닫기, 열기 기능 - PATCH
- [x] 마일스톤 삭제 기능 - DELETE
