### ISSUE TITLE
[BE] Issue API 구현

### ISSUE THREAD

**Issue by ninaaano** [hoongding/issue-tracker#62]
## 💡 Issue
이슈 관련 도메인, 레파지토리, 서비스 등 로직 구현

## 📝 Todo
- [x]  열린 이슈 조회
- [x]  닫힌 이슈 조회
- [x]  이슈 생성 페이지 요청
- [x]  이슈 생성
- [x]  이슈 상세 페이지
- [x]  이슈 열기/닫기
- [x]  이슈 제목 편집
- [ ]  이슈 코멘트 생성
- [ ]  이슈 코멘트 편집
- [ ]  이슈 코멘트 삭제
- [ ]  이슈 담당자 가져오기
- [ ]  이슈 담당자 선택
- [x]  이슈 레이블 가져오기
- [x]  이슈 레이블 선택
- [x]  이슈 마일스톤 가져오기
- [x]  이슈 마일스톤 선택
