### ISSUE TITLE
[BE] 2주차 피드백 학습하기

### ISSUE THREAD

**Issue by ninaaano** [hoongding/issue-tracker#90]
## 💡 Issue
2주차 피드백 관련 학습 키워드

------

구조가 헷갈린다면 클라이언트 <-> WAS, WAS <-> DB 간의 인바운드/아웃바운드 트래픽을 추적하면서 어떻게 통신이 흘러가는지 한번 되짚어보시는 것도 좋을 것 같습니다!

------

## 📝 Todo
- [ ] (인프라 그림 구조 개선) VPC의 IP 정보나 public, private subnet의 라우팅 테이블 규칙 적기
- [x] WAS는 이미 public IP를 가지고 있는데 IGW는 왜 필요할까요?
인터넷 게이트웨이는 무조건 필요합니다. 없으면 인터넷에 연결할 수 없습니다
IGW는 VPC와 인터넷 간의 트래픽 관리, 보안 강화, 확장성과 고가용성 제공을 위해 필요합니다
- [ ] 라우팅 테이블은 왜 필요한가요? 라우팅 규칙은 어떻게 설정해주셨나요?
- [x] private subnet에 별도로 NAT 구축은 필요없을까요?
private subnet은 인터넷에서 직접 엑세스 할 수 없습니다. EC2가 있으면 NAT를 사용해야하고 외부 인터넷으로 나가는 통신만 가능합니다. private subnet에는 공용 ip주소가 할당되지 않기 때문입니다. 인터넷에서 이 서브넷 안에있는 Ec2 인스턴스의 ip 주소를 알 수 없습니다.
- [ ] DB나 WAS 이중화. 클라이언트 <-> WAS <-> DB 간의 네트워크 구조
- [ ] @Transactional이란?

--------------------

+ 
- Spring Data JDBC는 stream()을 지원하지 않는다. 그럼 어떻게 해결해야할까?
